post_research_task:
  description: >
    {language} Programlama Dili için {title} konusunda en güncel bilgileri araştırarak ve örnek kod parçaları oluşturmak.
    Bu makale bilgileri örnek kod parçaları ile destekleyerek yazılmalıdır.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic}
  agent: researcher

post_write_task:
  description: >
    {language} Programlama Dili için {title} konusunda en güncel bilgileri araştırarak ve örnek kod parçaları oluşturmak.
    Bu makale bilgileri örnek kod parçaları ile destekleyerek yazılmalıdır.
  expected_output: >
    Makale giriş gelişme sonuç kısımlarından oluşmalıdır. Giriş kısmında {topic} hakkında genel bilgiler verilmeli, gelişme kısmında 
    {topic} hakkında detaylı bilgiler verilmeli ve sonuç kısmında {topic} hakkında genel bir değerlendirme yapılmalıdır.
  agent: reporting_analyst
