write_poem:
  description: >
    {topic} hakkında {sentence_count} satırdan oluşan bir şiir yaz. İşin içine biraz eğlence katmayı unutma.
  expected_output: >
    {topic} hakkında {sentence_count} satırdan oluşan bir şiir.
  agent: poem_writer
